### ISSUE TITLE
Error 403: Forbidden

### ISSUE THREAD

**Issue by RoGion** [avaapm/marveldataset2016#7]
Hello,
I am trying to download the dataset using Python 3.10  but no file is downloaded. I get a series of errors for each download  (below an example).

Traceback (most recent call last):
  File "E:\marveldataset2016-master\marveldataset2016-master\MARVEL_Download.py", line 103, in worker
    status = save_image(ID,JUST_IMAGE,currFolder)
  File "E:\marveldataset2016-master\marveldataset2016-master\MARVEL_Download.py", line 40, in save_image
    html = urlopen(url,timeout = 300).read()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Thanks for the help
Ionut

**Comment by primakov** [comment]
Yeah, some parts of the code in the repository are outdated.
There are changes you need to make to make it work:

#line2
#from urllib2 import urlopen
from urllib.request import Request, urlopen

#line 33
#sourceLink = "http://www.shipspotting.com/gallery/photo.php?lid="
sourceLink = "https://www.shipspotting.com/photos/"

#line40
#html = urlopen(url, timeout = 300).read()
req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
html = urlopen(req, timeout=300).read()
soup = BeautifulSoup(html, "lxml")

#line53
#f = urlopen(each)
req = Request(each, headers={'User-Agent': 'Mozilla/5.0'})
f = urlopen(req, timeout=300)

#line59
#out = file(os.path.join(outFolder,filename),"wb")
out = open(os.path.join(outFolder,filename),"wb")

Otherwise, just download my fork.
